# Workflow Configuration

> Generated by ab-harness-skill. Agents read this file at session start.
> Format: `KEY=value` or `KEY=ON|OFF`

## AI tools

TOOLS={{TOOLS}}

## Integrations

| Flag | Value | Notes |
|------|-------|-------|
| JIRA_TASKS | {{JIRA_TASKS}} | {{JIRA_NOTES}} |
| GITHUB_PULL_REQUESTS | {{GITHUB_PULL_REQUESTS}} | {{GITHUB_NOTES}} |
| CONFLUENCE | {{CONFLUENCE}} | {{CONFLUENCE_NOTES}} |

## Validation isolation (per tool)

| Tool | Mode |
|------|------|
| Cursor | {{VALIDATION_CURSOR}} |
| Claude | {{VALIDATION_CLAUDE}} |
| Codex | {{VALIDATION_CODEX}} |

Modes: `subagents` | `multi-session` | `script-only`

## Fallback paths (when integration OFF or MCP pending)

TASKS_FALLBACK={{TASKS_FALLBACK}}
DOCS_FALLBACK={{DOCS_FALLBACK}}
SPECS_DIR=.specs
LANE_COMMANDS=docs/workflow/lane-commands.json
HANDOFF_DIR=.specs/testing/handoff
REPORTS_DIR=.specs/testing/reports

## Tracker (when JIRA_TASKS=ON)

TRACKER_PREFIX={{TRACKER_PREFIX}}
TRACKER_MCP_SERVER={{TRACKER_MCP_SERVER}}

## Branches (adjust to your repo)

INTEGRATION_BRANCH={{INTEGRATION_BRANCH}}
PRODUCTION_BRANCH={{PRODUCTION_BRANCH}}

## MCP status

MCP_STATUS={{MCP_STATUS}}

## Project

PROJECT_NAME={{PROJECT_NAME}}
BOOTSTRAP_DATE={{BOOTSTRAP_DATE}}
