# Validation Lane Report — {{SLUG}} — {{DATE}}

> Consolidated by validation-lane merge from 5 runner evidence files.

{{TRACKER_LINE}}

## Results

| Runner | Status | Summary |
|--------|--------|---------|
| lint-build | _PASS / SKIP / FAIL / MISSING_ | |
| unit | _PASS / SKIP / FAIL / MISSING_ | |
| integration | _PASS / SKIP / FAIL / MISSING_ | |
| e2e | _PASS / SKIP / FAIL / MISSING_ | |
| uat | _PASS / SKIP / FAIL / MISSING_ | |

## Overall: _APROVADO / REPROVADO_

Handoff: `.specs/testing/handoff/{{SLUG}}.json`

---

_This file is generated by `npm run validation-lane:merge`. Do not hand-edit the final report._
